--- # Ergex config file for simulation 1

# This file allows control over the data processing pipeline without any need
# to edit the code.

# This section specifies the folder structure
data directory: "data/0_simulation/grid/time_optimal"
figure directory: "figs/0_simulation/grid/time_optimal"

# This section specifies data variables
data_type: "0_simulation"
data_variant: "grid"
n_agents: 10
n_samples: 5000
n_chains: 4
n_conditions: 2

# This section provides control over whether data needs to be re-read
readingdata:
  run: True

# This section provides control over whether user wants to re-run the Bayesian models
bayesian method:
  run: True

# This section provides control over whether plot data needs to be re-calculated
bracketing method:
  run: True
  calculate_indif_eta: True
  log_reg: True

# This section provides control over whether user wants to re-compute the JASP input
JASP input:
  run: True

# This section provides control over the various steps in the plotting pipeline
plots:
  run: True
  plot_passive: True
  plot_no_brainers: True
  plot_active: True
  plot_riskaversion_bracketing: True
  plot_riskaversion_bayesian: True
