data directory: data/2_full_data
data_type: real_data
data_variant: 2_full_data
extension: beh.tsv
figure directory: figs/2_full_data
input_path:
exclusion_criteria: [1, 2]
n_agents: 58
n_conditions: 2
qual: 3
readingdata:
  run: true
bayesian method:
  run: true
bracketing method:
  calculate_indif_eta: true
  log_reg: true
  run: false
JASP input:
  run: false
bayesfactor_analysis:
  run: false
  plot: true
  target: no_pooling
plots:
  run: true
  plot_passive: false
  plot_nobrainers: true
  plot_active: false
  plot_risk_aversion_bracketing: false
  plot_riskaversion_bayesian: false
  plot_pairwise: true
  plot_mcmc_samples: false
  plot_sensitivity_bayesian: false
  plot_model_selection: false
