JASP input:
  run: true
bayesfactor_analysis:
  plot: true
  run: true
  target: partial_pooling
bayesian method:
  run: true
bracketing method:
  calculate_indif_eta: true
  log_reg: true
  run: true
data directory: data/2_full_data
data_type: real_data
data_variant: 2_full_data
extension: beh.tsv
figure directory: figs/2_full_data
input_path:
n_agents: 60
n_conditions: 2
qual: 3
plots:
  plot_active: true
  plot_bayes: true
  plot_jasp_like: true
  plot_no_brainers: true
  plot_passive: true
  plot_riskaversion_bayesian: true
  plot_riskaversion_bracketing: true
  run: true
readingdata:
  run: true
